name: Qt CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
    build:
      strategy:
        matrix:
          os: [windows-latest]
      runs-on: ${{ matrix.os }}
      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Install Qt
          uses: jurplel/install-qt-action@v3
          with:
            version: 6.5.3
            arch:  win64_msvc2019_64
            # dir: D:\Qt\6.5.3\msvc2019_64

        - name: Set up Visual Studio environment
          uses: microsoft/setup-msbuild@v1.3.1
        
        - name: Configure Qt Environment
          shell: pwsh
          run: |
            # Set Qt environment variables
            echo "QTDIR=$env:RUNNER_WORKSPACE\Qt\6.5.3\msvc2019_64" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
            echo "PATH=$env:RUNNER_WORKSPACE\Qt\6.5.3\msvc2019_64\bin;$env:PATH" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

        - name: Prepare Build Directory
          shell: pwsh
          run: |
            if (Test-Path -Path "${{ github.workspace }}/build") {
              Remove-Item -Path "${{ github.workspace }}/build" -Recurse -Force
            }
            New-Item -ItemType Directory -Path "${{ github.workspace }}/build"
            
        - name: Configure and Build Project
          shell: cmd
          run: |
            call "C:\Program Files\microsoft visual studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat"
            cd ${{ github.workspace }}/build
            qmake ..
            nmake
        
        - name: Run Tests
          shell: cmd
          run: |
            call "C:\Program Files\microsoft visual studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat"
            cd ${{ github.workspace }}/build
            .\release\huehnerManager.exe
        
        - name: Package Artifacts
          if: runner.os == 'Windows' && github.ref == 'refs/heads/main'
          shell: pwsh
          run: |
            mkdir release
            Copy-Item "${{ github.workspace }}/build/release/huehnerManager.exe" -Destination "release/"
            Compress-Archive -Path release/* -DestinationPath huehnerManager-Windows.zip
        
        - name: Upload Release
          if: runner.os == 'Windows' && github.ref == 'refs/heads/main'
          uses: softprops/action-gh-release@v1
          with:
            files: huehnerManager-Windows.zip
            tag_name: v${{ github.sha }}
