name: Qt CI/CD

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        strategy:
            matrix:
                os: [windows-latest]
        runs-on: ${{ matrix.os }}
        steps:
            - name: Checkout code
            - uses: actions/checkout@v4

            - name: Install Qt
            - uses: jurplel/install-qt-action@v3
              with:
                version: 6.5.3
              arch:
                windows-latest: win64_msvc2019_64
            # 设置 Qt 环境变量
            - name: Set Qt Environment
              if: runner.os == 'Windows'
              shell: cmd
              run: |
                call "%QT_PATH%\bin\qtenv2.bat"
                echo "QT_DIR=%QT_PATH%" >> %GITHUB_ENV
            # 生成构建目录
            - name: Configure Project
              shell: bash
              run: |
                mkdir build
                cd build
                qmake ..

            # 编译项目
            - name: Build Project
              shell: bash
              run: |
                cd build
                nmake

            #运行测试
            - name: Run Tests
              shell: bash
              run: |
                 cd build
                 ./huehnerManager

            - name: Package Artifacts
              if: runner.os == 'Windows' && github.ref == 'refs/heads/main'
              run: |
                mkdir release
                cp build/release/huehnerManager.exe release/
                7z a huehnerManager-Windows.zip ./release/*

            - name: Upload Release
              if: runner.os == 'Windows' && github.ref == 'refs/heads/main'
              uses: softprops/action-gh-release@v1
              with:
                files: huehnerManager-Windows.zip
